In [1]:
import pandas as pd

In [28]:
df=pd.read_csv("G:/ml/recommender_system_based_on_similarity_of_movies/IMDB_Top250Engmovies2_OMDB_Detailed.csv")

In [29]:
df.head()

,Unnamed: 0,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,...,tomatoConsensus,tomatoUserMeter,tomatoUserRating,tomatoUserReviews,tomatoURL,DVD,BoxOffice,Production,Website,Response
0,1,The Shawshank Redemption,1994,R,14 Oct 1994,142 min,"Crime, Drama",Frank Darabont,"Stephen King (short story ""Rita Hayworth and S...","Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/shawshank_rede...,27 Jan 1998,NaN,Columbia Pictures,NaN,True
1,2,The Godfather,1972,R,24 Mar 1972,175 min,"Crime, Drama",Francis Ford Coppola,"Mario Puzo (screenplay), Francis Ford Coppola ...","Marlon Brando, Al Pacino, James Caan, Richard ...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather/,09 Oct 2001,NaN,Paramount Pictures,http://www.thegodfather.com,True
2,3,The Godfather: Part II,1974,R,20 Dec 1974,202 min,"Crime, Drama",Francis Ford Coppola,"Francis Ford Coppola (screenplay), Mario Puzo ...","Al Pacino, Robert Duvall, Diane Keaton, Robert...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/godfather_part...,24 May 2005,NaN,Paramount Pictures,http://www.thegodfather.com/,True
3,4,The Dark Knight,2008,PG-13,18 Jul 2008,152 min,"Action, Crime, Drama",Christopher Nolan,"Jonathan Nolan (screenplay), Christopher Nolan...","Christian Bale, Heath Ledger, Aaron Eckhart, M...",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/the_dark_knight/,09 Dec 2008,"$533,316,061",Warner Bros. Pictures/Legendary,http://thedarkknight.warnerbros.com/,True
4,5,12 Angry Men,1957,APPROVED,01 Apr 1957,96 min,"Crime, Drama",Sidney Lumet,"Reginald Rose (story), Reginald Rose (screenplay)","Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",...,NaN,NaN,NaN,NaN,http://www.rottentomatoes.com/m/1000013-12_ang...,06 Mar 2001,NaN,Criterion Collection,http://www.criterion.com/films/27871-12-angry-men,True

In [30]:
df=df[["Title","Director","Actors","Plot","Genre"]]

In [31]:
df.head()

,Title,Director,Actors,Plot,Genre
0,The Shawshank Redemption,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...",Two imprisoned men bond over a number of years...,"Crime, Drama"
1,The Godfather,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Richard ...",The aging patriarch of an organized crime dyna...,"Crime, Drama"
2,The Godfather: Part II,Francis Ford Coppola,"Al Pacino, Robert Duvall, Diane Keaton, Robert...",The early life and career of Vito Corleone in ...,"Crime, Drama"
3,The Dark Knight,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...",When the menace known as the Joker emerges fro...,"Action, Crime, Drama"
4,12 Angry Men,Sidney Lumet,"Martin Balsam, John Fiedler, Lee J. Cobb, E.G....",A jury holdout attempts to prevent a miscarria...,"Crime, Drama"

In [32]:
df['Actors'] = df['Actors'].map(lambda x: x.split(',')[:3])

df['Genre'] = df['Genre'].map(lambda x: x.lower().split(','))

df['Director'] = df['Director'].map(lambda x: x.split(' '))

In [33]:
for index, row in df.iterrows():
    row['Actors'] = [x.lower().replace(' ','') for x in row['Actors']]
    row['Director'] = ''.join(row['Director']).lower()

In [34]:
from rake_nltk import Rake
df["keywords"]=""

for index,row in df.iterrows():
    plot= row["Plot"]
    r =Rake()
    r.extract_keywords_from_text(plot)
    keywords_dict_scores= r.get_word_degrees()
    row["keywords"]=list(keywords_dict_scores.keys())
    
df.drop(columns=["Plot"],inplace=True)

In [35]:
df.head()

,Title,Director,Actors,Genre,keywords
0,The Shawshank Redemption,frankdarabont,"[timrobbins, morganfreeman, bobgunton]","[crime, drama]","[common, decency, acts, eventual, redemption, ..."
1,The Godfather,francisfordcoppola,"[marlonbrando, alpacino, jamescaan]","[crime, drama]","[aging, patriarch, organized, crime, dynasty, ..."
2,The Godfather: Part II,francisfordcoppola,"[alpacino, robertduvall, dianekeaton]","[crime, drama]","[son, vito, corleone, grip, early, life, caree..."
3,The Dark Knight,christophernolan,"[christianbale, heathledger, aaroneckhart]","[action, crime, drama]","[mysterious, past, menace, known, ability, gre..."
4,12 Angry Men,sidneylumet,"[martinbalsam, johnfiedler, leej.cobb]","[crime, drama]","[prevent, justice, reconsider, miscarriage, fo..."

In [37]:
df.set_index("Title",inplace=True)

In [39]:
df.head()

,Director,Actors,Genre,keywords
Title,,,,
The Shawshank Redemption,frankdarabont,"[timrobbins, morganfreeman, bobgunton]","[crime, drama]","[common, decency, acts, eventual, redemption, ..."
The Godfather,francisfordcoppola,"[marlonbrando, alpacino, jamescaan]","[crime, drama]","[aging, patriarch, organized, crime, dynasty, ..."
The Godfather: Part II,francisfordcoppola,"[alpacino, robertduvall, dianekeaton]","[crime, drama]","[son, vito, corleone, grip, early, life, caree..."
The Dark Knight,christophernolan,"[christianbale, heathledger, aaroneckhart]","[action, crime, drama]","[mysterious, past, menace, known, ability, gre..."
12 Angry Men,sidneylumet,"[martinbalsam, johnfiedler, leej.cobb]","[crime, drama]","[prevent, justice, reconsider, miscarriage, fo..."

In [40]:
df['bag_of_words'] = ''
columns = df.columns
for index, row in df.iterrows():
    words = ''
    for col in columns:
        if col != 'Director':
            words = words + ' '.join(row[col])+ ' '
        else:
            words = words + row[col]+ ' '
    row['bag_of_words'] = words
    
df.drop(columns = [col for col in df.columns if col!= 'bag_of_words'], inplace = True)

In [41]:
df.head()

                                                               bag_of_words
Title
The Shawshank Redemption  frankdarabont timrobbins morganfreeman bobgunt...
The Godfather             francisfordcoppola marlonbrando alpacino james...
The Godfather: Part II    francisfordcoppola alpacino robertduvall diane...
The Dark Knight           christophernolan christianbale heathledger aar...
12 Angry Men              sidneylumet martinbalsam johnfiedler leej.cobb...

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

count = CountVectorizer()
count_matrix = count.fit_transform(df['bag_of_words'])

# generating the cosine similarity matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)

In [44]:
cosine_sim

array([[ 1.        ,  0.15789474,  0.13764944, ...,  0.05263158,
         0.05263158,  0.05564149],
       [ 0.15789474,  1.        ,  0.36706517, ...,  0.05263158,
         0.05263158,  0.05564149],
       [ 0.13764944,  0.36706517,  1.        , ...,  0.04588315,
         0.04588315,  0.04850713],
       ...,
       [ 0.05263158,  0.05263158,  0.04588315, ...,  1.        ,
         0.05263158,  0.05564149],
       [ 0.05263158,  0.05263158,  0.04588315, ...,  0.05263158,
         1.        ,  0.05564149],
       [ 0.05564149,  0.05564149,  0.04850713, ...,  0.05564149,
         0.05564149,  1.        ]])

In [45]:
indices = pd.Series(df.index)

#  defining the function that takes in movie title 
# as input and returns the top 10 recommended movies
def recommendations(title, cosine_sim = cosine_sim):
    
    # initializing the empty list of recommended movies
    recommended_movies = []
    
    # gettin the index of the movie that matches the title
    idx = indices[indices == title].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar movies
    top_10_indexes = list(score_series.iloc[1:11].index)
    
    # populating the list with the titles of the best 10 matching movies
    for i in top_10_indexes:
        recommended_movies.append(list(df.index)[i])
        
    return recommended_movies

In [47]:
recommendations("The Godfather")

['The Godfather: Part II',
 'Scarface',
 'Fargo',
 'Rope',
 'On the Waterfront',
 'Goodfellas',
 'Cool Hand Luke',
 'Baby Driver',
 'Casino',
 'A Clockwork Orange']